### ISSUE TITLE
Add additional instructions on how to run on IJ

### ISSUE THREAD

**Issue by armgitaar** [alpas/alpasdev#52]
A fresh install of IJ runs Java 1.8. User has to find where Java 9 is installed and update SDK path. Also, IJ sees Gradle and prompts an install - the user will have to take action and install in order to run.

**Comment by ashokgelal** [comment]
Resolved by https://github.com/alpas/alpasdev/commit/597c74dd0a8e2b425ea6d3f5e1e92a6244514d96
